### ISSUE TITLE
cflib not building

### ISSUE THREAD

**Issue by th-otto** [freemint/cflib#2]
There seems to be a problem again with the key:

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157

W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)

W: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/trusty/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157

W: Some index files failed to download. They have been ignored, or old ones used instead.

+sudo apt-get install -y gcc-m68k-atari-mint binutils-m68k-atari-mint mintlib-m68k-atari-mint gemlib-m68k-atari-mint

E: Unable to locate package gcc-m68k-atari-mint

E: Unable to locate package binutils-m68k-atari-mint

E: Unable to locate package mintlib-m68k-atari-mint

E: Unable to locate package gemlib-m68k-atari-mint
```

**Comment by th-otto** [comment]
Just restarted the latest build in gemlib, and it fails with the same error. Maybe something wrong with ppa again?

**Comment by mikrosk** [comment]
Isn't possible that @vinriviere has disabled `trusty` repos?

**Comment by th-otto** [comment]
Maybe. We should switch to xenial for this libraries anyway.

**Comment by mikrosk** [comment]
Gemlib is failing too: https://travis-ci.org/freemint/gemlib

Agreed, xenial transition is easy but it needs to be done for all projects to avoid confusion.

**Comment by th-otto** [comment]
> Gemlib is failing too: https://travis-ci.org/freemint/gemlib

Yes, that was the last commit from Oct 4, where it succeeded. I restarted it a few minutes ago, just to check for that error.

**Comment by vinriviere** [comment]
> Isn't possible that @vinriviere has disabled `trusty` repos?

Indeed, I removed `trusty` packages from my PPA some time ago, as that distribution is officially obsolete.  I wasn't aware that some build chains were still using it. In most cases, upgrading Travis CI builds to `xenial` is trivial.

**Comment by th-otto** [comment]
Yes, sure. Will change that soon, have to push some other changes first.
