### ISSUE TITLE
make install without hcp

### ISSUE THREAD

**Issue by vinriviere** [freemint/cflib#4]
It's currenly impossible to do a successful "make install" without the `hcp` tool being installed. Is this expected? If not, this should be fixed.

**Comment by th-otto** [comment]
There is a rule in the Makefile to checkfor HCP:https://github.com/freemint/cflib/blob/df64cf30c00e3e9981d864b580f7fd00626070dc/Makefile#L81

Doesn't that work?

**Comment by th-otto** [comment]
Ah, never mind. install then fails because of the missing cflib.hyp. Fixed now, but i would recommend to install hcp anyway in your script, because otherwise only the cflib.stg can be installed.

**Comment by vinriviere** [comment]
Thanks.
Indeed, I will have to add `hcp` to the cross-tools to generate `cflib.hyp`. However, that help file is not critical, particularly in a cross environment.
